### PR TITLE
Font Awesome Version 5.0.2

### PR DESCRIPTION
**Pull request by ravihariharan**
Version 5.0.2
Additions :
.fa-amazon-pay
.fa-cc-amazon-pay
.fa-ethereum
.fa-korvue
.fa-stopwatch

### CODE REVIEW

**Comment by melloware** [comment]
Ravi if you look at my PR I build the whole font awesome page dynamically. So once the version is upgraded it picks up and displays the new icons by reading the names out of the font!

**Comment by melloware** [comment]
https://github.com/primefaces/showcase/pull/57

**Comment by ravihariharan** [comment]
@melloware  i saw the code  but since it was not in the master i made a temporary fix until #57 was merged.

**Comment by tandraschko** [comment]
Applied the PR from @melloware

**Pull request closed without merging**
