### PR TITLE
Moved showcase location

### PR DESCRIPTION
**Pull request by melloware**

### CODE REVIEW

**Comment by Emkas** [comment]
Would be nice, to have this update on main README :-)

BTW. Do you know how to get PF 8.0 showcase? Legacy is up to 7.2 and it looks like the new one (from this PR) is from 11.

**Comment by melloware** [comment]
Yep you can get 8.0 showcase here: https://github.com/primefaces/primefaces-showcase/releases/tag/v8.0

**Comment by Emkas** [comment]
> Yep you can get 8.0 showcase here: https://github.com/primefaces/primefaces-showcase/releases/tag/v8.0

This goes to 404 :-) (same without `tag/v.8.0`)

**Comment by melloware** [comment]
I just clicked that link and it took me right to to the Showcase V8 source code?

image

**Comment by pzygielo** [comment]
> I just clicked that link and it took me right to to the Showcase V8 source code?
> 
> image

Can you see **Private** near the repo name?

**Comment by melloware** [comment]
AHHH ha it lets me see it because I am a committer.  Whoops!  I downloaded the zip for you.
[primefaces-showcase-8.0.zip](https://github.com/primefaces/primefaces-showcase-legacy/files/9189953/primefaces-showcase-8.0.zip)

**Comment by Emkas** [comment]
OK. Now it's clear. As far as I understand there's no public source for showcases 7.0, 8.0 and X.

Strange it goes that way. I know that a showcase isn't something crucial, but we use it for legacy projects, to sometimes tell ourselves something like: OK, that doesn't work on a showcase as well. So on our dev servers I have PF showcases of 6.0-6.2 (last year it was even 5.3 :-))

> Legacy is up to 7.2 and it looks like the new one (from this PR) is from 11.

Corrected (typo): up to 6.2.

**Pull request merged**
